### ISSUE TITLE
Not able to convert to pdf

### ISSUE THREAD

**Issue by Krishnamurthy-sfdx** [Phoenix124/scribd-downloader#10]
I ran this command and I get the below error.
`scribdl -p  https://www.scribd.com/read/189087235/Confessions-of-a-Casting-Director-Help-Actors-Land-Any-Role-with-Secrets-from-Inside-the-Audition-Room`
Error:
```
 File "C:\Users\Raghav\AppData\Local\Programs\Python\Python38\lib\codecs.py", line 504, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 642: invalid start byte
```

**Comment by thefernanbri** [comment]
I managed to convert .md to .pdf with md-to-pdf
3.1.1
https://www.npmjs.com/package/md-to-pdf

**Comment by Phoenix124** [comment]
@Krishnamurthy-sfdx check pls your installation, i've already tried
<img width="429" alt="Screenshot 2023-04-02 at 18 10 20" src="https://user-images.githubusercontent.com/19951392/229361775-54ba88fc-eeb8-41b0-8ebc-d8f716b228e6.png">
Try to use python > 3.11
