### ISSUE TITLE
Encoding errors

### ISSUE THREAD

**Issue by thefernanbri** [Phoenix124/scribd-downloader#11]
I can't download the books

Follow the errors

Books I tried to download
https://en.scribd.com/read/375814859/Injusticia-epistemica
https://en.scribd.com/read/470645698/O-Direito-e-Suas-Interfaces-com-a-Psicologia-e-a-Neurociencia
https://www.scribd.com/read/460369898/Somos-nosso-cerebro-Neurociencias-subjetividade-cultura

![Captura de Tela (236)](https://user-images.githubusercontent.com/69486462/93725610-f900f380-fb86-11ea-8678-2187a0aa689d.png)
![Captura de Tela (237)](https://user-images.githubusercontent.com/69486462/93725613-fa322080-fb86-11ea-976f-6836946120c2.png)

I only succeeded in downloading a book (since it is mostly composed of images), however when it came to transforming into .PDF a new error occurred:

Link: https://en.scribd.com/read/419837886/Big-Book-of-TV-Theme-Songs-2nd-Edition

![Captura de Tela (238)](https://user-images.githubusercontent.com/69486462/93725988-c9071f80-fb89-11ea-93a8-9a4624dbb1d2.png)

ADDED: I managed to convert .md to .pdf with md-to-pdf
3.1.1
https://www.npmjs.com/package/md-to-pdf

**Comment by Phoenix124** [comment]
@thefernanbri I've already checked, it's working fine
if you have trouble with cropped images in pdf use script
```
cd dir_with_all_image_files && img2pdf $(ls -tr *.jpg) -o path_to_pdf_output_file.pdf
``
