### ISSUE TITLE
no library called "cairo" was found

### ISSUE THREAD

**Issue by rubencanovaca** [Phoenix124/scribd-downloader#13]
![image](https://user-images.githubusercontent.com/3774332/98836826-725bea80-2442-11eb-901c-58bf31fe87f4.png)

**Comment by johndpope** [comment]
see my PR

**Comment by johndpope** [comment]
Did you try installing / https://stackoverflow.com/questions/9526375/how-to-install-cairo-on-windows / again I’d recommend installing Linux subsystem. This downloaded isn’t just downloading it’s taking images and spitting out PDFs.
