### ISSUE TITLE
Cropped pages in the pdf

### ISSUE THREAD

**Issue by buscon** [Phoenix124/scribd-downloader#14]
When I download a book such as:
scribdl -c credentials.txt -i -p https://www.scribd.com/read/269690225/Jazz-Standards-for-Solo-Guitar

The single images are downloaded correctly, but the pages in the generated pdf are weirdly cropped, only the upper corner of a page is visible. Maybe a problem of resolution? How can I avoid such problem?

Thanks.

**Comment by johnnyontheweb** [comment]
Same problem for me, anyone?

**Comment by buscon** [comment]
I found a workaround that might be useful to other people: after you downloaded all the pages, you do:
`cd dir_with_all_image_files
img2pdf $(ls -tr *.jpg) -o path_to_pdf_output_file.pdf
`
This way you get a pdf without cropped images.
