### ISSUE TITLE
KeyError: 'class'

### ISSUE THREAD

**Issue by itsbkm** [Phoenix124/scribd-downloader#27]
Python Version : 3.9.4
Scridbdl Version : Latest Version
Mac OS : 10.15.7
Scribd Premium Account
Command : 
~ % scribdl -c Sites/scribd-downloader/scribd_credentials.txt https://www.scribd.com/book/253264900/Sapiens-A-Brief-History-of-Humankind 

Output:
Traceback (most recent call last):
  File "/usr/local/bin/scribdl", line 33, in <module>
    sys.exit(load_entry_point('scribd-downloader==1.3.1', 'console_scripts', 'scribdl')())
  File "/usr/local/lib/python3.9/site-packages/scribd_downloader-1.3.1-py3.9.egg/scribdl/command_line.py", line 53, in _command_line
  File "/usr/local/lib/python3.9/site-packages/scribd_downloader-1.3.1-py3.9.egg/scribdl/downloader.py", line 28, in __init__
  File "/usr/local/lib/python3.9/site-packages/scribd_downloader-1.3.1-py3.9.egg/scribdl/downloader.py", line 97, in is_book
  File "/usr/local/lib/python3.9/site-packages/beautifulsoup4-4.9.3-py3.9.egg/bs4/element.py", line 1406, in __getitem__
    return self.attrs[key]
KeyError: 'class'

**Comment by juancaiman** [comment]
I cant help you with the error, though if you want to download that book "brief history of humankind" check this website...
https://1lib.fr/book/2470525/8fa36f

**Comment by itsbkm** [comment]
> I cant help you with the error, though if you want to download that book "brief history of humankind" check this website...
> https://1lib.fr/book/2470525/8fa36f

Thank You so much!

**Comment by FrankFacundo** [comment]
> I cant help you with the error, though if you want to download that book "brief history of humankind" check this website...
> https://1lib.fr/book/2470525/8fa36f

Could you tell us how do you solve the error please?

**Comment by itsbkm** [comment]
> > I cant help you with the error, though if you want to download that book "brief history of humankind" check this website...
> > https://1lib.fr/book/2470525/8fa36f
> 
> Could you tell us how do you solve the error please?

I couldnt fix the issue and simply started using this https://1lib.fr/book/2470525/8fa36f website

**Comment by kyle8581** [comment]
I think you entered invalid url. I encounterd same error `Key Error : 'class'`,and  I found that the url should be `scribd.com/read/~` not `scribd.com/bood/~`. You should click the `Continue Reading` button and copy the url.
