### ISSUE TITLE
"No more content being exposed by Scribd!"

### ISSUE THREAD

**Issue by Geremia** [Phoenix124/scribd-downloader#38]
When I run, for example

    scribdl https://www.scribd.com/read/481551943/Mario-Cuomo-The-Myth-and-the-Man
it'll download the first chapter or so, but give this error: "No more content being exposed by Scribd!"

However, on the website I can flip through the whole book.

I'm using master (be0f3c3) with Python 3.10.

**Comment by Geremia** [comment]
This was due to bad values in const.py file; cf. #33.

**Comment by hawkeye2nd** [comment]
Tried recommended credential update in #33  - still no go. Limits after 2 chapters (36 pages)

**Comment by jaan143** [comment]
@Geremia  so that issue solve in your side ?

**Comment by Geremia** [comment]
@jaan143 Yes, it's solved for me. Are you still having issues?

**Comment by jaan143** [comment]
@Geremia  i am still getting the issue it just downloading around 20 pages only
can you please help me about it
you can give me your email or any live chate id

**Comment by Geremia** [comment]
@jaan143 Did you re-run re-run `python3 setup.py install` after modifying [`const.py`](https://github.com/Phoenix124/scribd-downloader/blob/master/scribdl/const.py)?

See my comment [here](https://github.com/Phoenix124/scribd-downloader/issues/33#issuecomment-955091341).

**Comment by jaan143** [comment]
@Geremia  Dear i did it this one today again evan i downloaded fresh script and update const.py file and then i install python setup.py and after that when i command to download book i am getting this error

(process:23964): GLib-GIO-WARNING **: 12:35:42.914: Unexpectedly, UWP app `36059XiaoyaStudio.RealeBooksReader_2.0.1.0_x86__ngh7ertwt50re' (AUMId `36059XiaoyaStudio.RealeBooksReader_ngh7ertwt50re!REALEBOOKSREADER') supports 32 extensions but has no verbs
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\Scripts\scribdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('scribd-downloader==1.3.1', 'console_scripts', 'scribdl')())
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\scribd_downloader-1.3.1-py3.9.egg\scribdl\command_line.py", line 53, in _command_line
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\scribd_downloader-1.3.1-py3.9.egg\scribdl\downloader.py", line 28, in __init__
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\scribd_downloader-1.3.1-py3.9.egg\scribdl\downloader.py", line 97, in is_book
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\bs4\element.py", line 1406, in __getitem__
    return self.attrs[key]
KeyError: 'class'

**Comment by Geremia** [comment]
@jaan143 That sounds like a different issue. Perhaps there's a related issue already posted here for that. If not, open a new one;  maybe it's a bug.

**Comment by hawkeye2nd** [comment]
I modified it, but took a second look and saw the session cookie string was incorrect, while the expire was right. Changed it, reran the script, works great now. Important to double check everything!

> @jaan143 Did you re-run re-run `python3 setup.py install` after modifying [`const.py`](https://github.com/Phoenix124/scribd-downloader/blob/master/scribdl/const.py)?
> 
> See my comment [here](https://github.com/Phoenix124/scribd-downloader/issues/33#issuecomment-955091341).

**Comment by jaan143** [comment]
@Geremia  @hawkeye2nd  yes after modified const.py file i re run python setup.py install and it was install successfully without giving any error but i got error again then i install python 3.10 version which Geremia is using and i install all dependencies in this version and after that script working fine

**Comment by jaan143** [comment]
@Geremia  @hawkeye2nd  Did you guys notice that script is missing some text lines in programming books ?
i am facing that issue with 3 programming books and these all have missing some lines which is in codes style

can anyone fix that if i point out exactly which book and which lines are missing ?

**Comment by Geremia** [comment]
@jaan143 What "missing" "text lines" are you referring to?

**Comment by jaan143** [comment]
@Geremia  its not downloading complete book. its missing some lines like this
example these lines are missing 
dups = df.duplicated()
print(dups.any())
File_heart_first_record = file_heart.drop_duplicates (subset = ["Age", 
"Cholesterol", Etc], keep="first")

**Comment by SigmaDuck894** [comment]
Hey @Geremia , i did modify the const.py file, but how to re run the `setup.py`? Do i need to do anything or just click it? I tried clicking it but nothing happen. I still cant download the full book.

**Comment by SigmaDuck894** [comment]
I modified the `const.py` then tried re-running `python3 setup.py install` by running a cmd file as administrator. However, it still doesnt work

**Comment by Geremia** [comment]
@SigmaDuck894 

> I modified the `const.py` then tried re-running `python3 setup.py install` by running a cmd file as administrator. However, it still doesnt work

You're probably using expired `_scribd_session` and `_scribd_expire` cookies. Find the recent ones again (see [video](https://raw.githubusercontent.com/KalimAmzad/Scribd-Premium-Book-PDF-Downloader/e58f51811a74b60b4da8d8d20bea61ed9bfaf416/Scribd%20Premium%20Book%20Download.mp4)), update `const.py` accordingly, and re-run `python3 setup.py install` again.

**Comment by jaan143** [comment]
@Geremia  its not downloading complete book which is more than 500 pages
did you notice that ? and you have solution for it ?

**Comment by jaan143** [comment]
script is missing tables diagrams

**Comment by jaan143** [comment]
@hawkeye2nd will you tell me which type of cookies are perfect ?
my cookies are expired and i tried many cookies but i got error
