### ISSUE TITLE
Downloader Won't Even Install

### ISSUE THREAD

**Issue by Anarchy221** [Phoenix124/scribd-downloader#9]
When I Try The Install Command It Shows This In Red...

Could not find a version that satisfies the requirement scribd-downloader (from versions: none)
ERROR: No matching distribution found for scribd-downloader
![Screenshot_1](https://user-images.githubusercontent.com/56741330/85492145-89668100-b5f6-11ea-918f-828b90a1869c.jpg)

**Comment by theothersophie** [comment]
i worked around this by installing the development version (download the repository, run shell in it and `python setup.py install`). You also have to get GTK+ libraries to make it work. Similar to the step 4 here

https://weasyprint.readthedocs.io/en/stable/install.html#step-4-install-the-gtk-libraries

**Comment by Anarchy221** [comment]
> i worked around this by installing the development version (download the repository, run shell in it and `python setup.py install`). You also have to get GTK+ libraries to make it work. Similar to the step 4 here
> 
> https://weasyprint.readthedocs.io/en/stable/install.html#step-4-install-the-gtk-libraries

Oh, Thanks a Lot Mate...

Btw, Do I Need To Install Weasyprint Also ? or Just The GTK+ Libraries ?

**Comment by theothersophie** [comment]
Just the GTK+ libraries, WeasyPrint is irrelevant. Did you get it working?

**Comment by Anarchy221** [comment]
Aah, Installed It, But Haven't Tried Downloading Though...

**Comment by Anarchy221** [comment]
@theothersophie , Still The Same Problem... Even The Development Version Won't Install... Shows That Same Red Message... This Is So Annoying...

**Comment by Anarchy221** [comment]
@theothersophie, Any Other Way To Install This ?

**Comment by theothersophie** [comment]
What's the exact error message you get? You're trying to install it using `py setup.py`?

**Comment by Anarchy221** [comment]
@theothersophie, This Is What I Get...

![Screenshot_1](https://user-images.githubusercontent.com/56741330/87246046-57fe0a00-c46c-11ea-9570-263881a481e2.jpg)

**Comment by theothersophie** [comment]
you're in the wrong directory. You have cd into scribd-downloader-master. You don't need -m pip either.

**Comment by Anarchy221** [comment]
OKay, I Don't Understand What I'm Doing Wrong... 
![Screenshot_2](https://user-images.githubusercontent.com/56741330/87256200-62db8d80-c4b2-11ea-89f0-fb0b851a9b2c.jpg)
Nothing is Happening...
I'll Probably Give Up... This Is So Frustrating...
Sorry For Wasting Your Time, And Thanks a Lot For Trying To Help... I'm Just Too Stupid... 😭

**Comment by theothersophie** [comment]
you used `py` before, so try `py setup.py install`, the python command can vary from system to system depending on your setup.

**Comment by Anarchy221** [comment]
@theothersophie, Same... Nothing Happens...

![Screenshot_1](https://user-images.githubusercontent.com/56741330/87552621-c1338680-c6d3-11ea-855a-a999e99baee5.jpg)

**Comment by Testedbytime** [comment]
Hi, I followed your steps: succesfully installed dev version and GTK+ installer from latest sourceforge. Then I begun to get all sorts of library dependency warnings (too many to quote here) so I installed the missing libraries each time it asked for one. WeasyInstaller is required per one of the errors. But then I got

OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

at which point I gave up, running pip install on those two does nothing.

**Comment by nokeechia** [comment]
@Testedbytime 
You need to download the GTK+ dependencies to get the libcairo-2 dependencies.
After you install this, I used MSYS2 you will havee to use pacman to install libcairo2.

Please read https://weasyprint.readthedocs.io/en/stable/install.html#step-4-install-the-gtk-libraries

**Comment by Anarchy221** [comment]
Yeah, Too Many Things To Install... This Is Seriously Painful...

**Comment by megargayu** [comment]
On windows I managed to do it like this:

1. Download the development version (download ZIP or clone using `git`) and navigate to that directory in `cmd`. 
2. Run `python setup.py install` in the directory
3. Install [this](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases) (download the latest release's exe files and run both of them)
4. It should work!

**Comment by pakhi001** [comment]
> 
> 
> On windows I managed to do it like this:
> 
>     1. Download the development version (download ZIP or clone using `git`) and navigate to that directory in `cmd`.
> 
>     2. Run `python setup.py install` in the directory
> 
>     3. Install [this](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases) (download the latest release's exe files and run both of them)
> 
>     4. It should work!

Hey! Using the first two steps i was able to install, but it still shows "scribd" is not recognized as a command. What can I do?

**Comment by pakhi001** [comment]
> 
> 
> Just the GTK+ libraries, WeasyPrint is irrelevant. Did you get it working?

I installed the development version but it still displays that scribdl is not recognized. Any idea what could be wrong?

**Comment by megargayu** [comment]
> Hey! Using the first two steps i was able to install, but it still shows "scribd" is not recognized as a command. What can I do?
@pakhi001 

Well... the program runs when you type the command `scribdl`, not `scribd` - try that instead.

**Comment by pakhi001** [comment]
> 
> 
> > Hey! Using the first two steps i was able to install, but it still shows "scribd" is not recognized as a command. What can I do?
> 
> Well... the program runs when you type the command `scribdl`, not `scribd` - try that instead.

Yes, thanks, I identified that mistake and got it running, but it still wont download books or audiobooks, though it is now working perfectly for documents. I tried using the -c and passing my credentials in a txt file, but it was showing error that way, whereas when I put in my scribd session and scribd expire in the const.py, there was no error but it simply displayed a message "Extracting to Listen_to_title.txt" and then nothing happened. So, if you could help me out with this, I would be very grateful

**Comment by megargayu** [comment]
> > > Hey! Using the first two steps i was able to install, but it still shows "scribd" is not recognized as a command. What can I do?
> > 
> > 
> > Well... the program runs when you type the command `scribdl`, not `scribd` - try that instead.
> 
> Yes, thanks, I identified that mistake and got it running, but it still wont download books or audiobooks, though it is now working perfectly for documents. I tried using the -c and passing my credentials in a txt file, but it was showing error that way, whereas when I put in my scribd session and scribd expire in the const.py, there was no error but it simply displayed a message "Extracting to Listen_to_title.txt" and then nothing happened. So, if you could help me out with this, I would be very grateful

Well, I don't really know how this program works, and I don't have enough time to dive into it (also, I'm just too lazy). I would create a new issue or ask the contributors about your issue.

**Comment by KaKi87** [comment]
Hello,

Would it be possible to put this package back on the repository so that users wouldn't need building from source ?

Thanks

**Comment by yhw9102** [comment]
when i run >python setup.py install, there is error like this, please help  

 line 11, in <module>
    long_description = f.read()
                       ^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 88: illegal multibyte sequence

**Comment by Phoenix124** [comment]
Try to use latest `python > 3.11`, first start `pip install scribd-downloader ` than `python setup.py install`

**Comment by 3xploiton3** [comment]
> Try to use latest `python > 3.11`, first start `pip install scribd-downloader ` than `python setup.py install`

i follow your guide, then got this error,

![image](https://github.com/Phoenix124/scribd-downloader/assets/19517680/4bc665be-e8e5-407a-833c-069e42157d8a)
